force-app/main/default/objects/P__c/P__c.object-meta.xml
<CustomObject>
    <description>Object created for the Pull report creation; R-23768</description>
    <label>Pull</label>
    <nameField>
        <displayFormat>Pull-{000000}</displayFormat>
        <label>Pull Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pulls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P__c/fields/DS__c.field-meta.xml
<CustomField>
    <fullName>DS__c</fullName>
    <label>Current Pull: Date Job Started</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/P__c/fields/I1__c.field-meta.xml
<CustomField>
    <fullName>I1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake Gas 1 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Intake Gas 1 Serial #)</relationshipLabel>
    <relationshipName>Pulls_IntkGs_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/I2__c.field-meta.xml
<CustomField>
    <fullName>I2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake Gas 2 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Intake Gas 2 Serial #)</relationshipLabel>
    <relationshipName>Pulls_IntkGas_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal LT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Seal LT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Seal_LT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/LL__c.field-meta.xml
<CustomField>
    <fullName>LL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lease/Well Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Pulls</relationshipLabel>
    <relationshipName>Pulls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/M__c.field-meta.xml
<CustomField>
    <fullName>M__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MLC Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (MLC Serial #)</relationshipLabel>
    <relationshipName>Pulls_MLC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/MI__c.field-meta.xml
<CustomField>
    <fullName>MI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor CT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Motor CT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Motor_CT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/MN__c.field-meta.xml
<CustomField>
    <fullName>MN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor UT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Motor UT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Motor_UT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/MQ__c.field-meta.xml
<CustomField>
    <fullName>MQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor LT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Motor LT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Motors_LT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P1__c.field-meta.xml
<CustomField>
    <fullName>P1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 1 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls</relationshipLabel>
    <relationshipName>Pulls_Pump_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P2__c.field-meta.xml
<CustomField>
    <fullName>P2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 2 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 2 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P3__c.field-meta.xml
<CustomField>
    <fullName>P3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 3 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 3 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P4__c.field-meta.xml
<CustomField>
    <fullName>P4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 4 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 4 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P5__c.field-meta.xml
<CustomField>
    <fullName>P5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 5 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 5 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P6__c.field-meta.xml
<CustomField>
    <fullName>P6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 6 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 6 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P__c.field-meta.xml
<CustomField>
    <fullName>P__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/P__c/fields/PR__c.field-meta.xml
<CustomField>
    <fullName>PR__c</fullName>
    <label>Pull Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Grounded Down Hole</fullName>
            </value>
            <value>
                <fullName>High Amps / No Start</fullName>
            </value>
            <value>
                <fullName>Surface Power System Issue</fullName>
            </value>
            <value>
                <fullName>Converto to Other Lift Method</fullName>
            </value>
            <value>
                <fullName>Converto to Injection</fullName>
            </value>
            <value>
                <fullName>Abandoned / Shut-In</fullName>
            </value>
            <value>
                <fullName>Low/No Production</fullName>
            </value>
            <value>
                <fullName>Well Work Over</fullName>
            </value>
            <value>
                <fullName>Well Test Ended</fullName>
            </value>
            <value>
                <fullName>Resize</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pro-Active Pull</fullName>
            </value>
            <value>
                <fullName>Insufficient Information</fullName>
            </value>
            <value>
                <fullName>Power System Change out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P__c/fields/SR__c.field-meta.xml
<CustomField>
    <fullName>SR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Sensor Serial #)</relationshipLabel>
    <relationshipName>Pulls_Sensor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal UT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Seal UT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Seal_UT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GE_AL_UpdateWellEquipmentRunDataBatch.cls
/*
Req: R-25681

Class Name              :        GE_AL_UpdateWellEquipmentRunDataBatch
Class called in         :        GE_AL_wellRunscheduleUpdateBatch
Purpose                 :        To update well run data record under the location and Equipment Run data on the Installed Product record
Test class              :        GE_AL_WellEquipmentRunDataBatch_TEST
Created on              :        5/17/2017  
*/

global class GE_AL_UpdateWellEquipmentRunDataBatch implements Database.Batchable<sObject>{
    
    List<GE_AL_Well_Run_Data__c> wrderrorlist = new List<GE_AL_Well_Run_Data__c>();
    List<GE_AL_Equipment_Run_Data__c> erderrorlist = null;
    
    global Database.querylocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([select id,LL__c,DS__c,PR__c,P1__c,P2__c,P3__c,P4__c,P5__c,P6__c,I1__c,I2__c,SU__c,L__c,MN__c,MI__c,MQ__c,SR__c,M__c from P__c where CreatedDate = TODAY]);
    }
    
    global void execute(Database.BatchableContext BC, list<P__c> scope) {
        
        Map<ID, P__c> pullmap = new Map<ID, P__c>();
        
        for(P__c pull: scope)
        {
            if (pull.LL__c != Null)
            {
                pullMap.put(pull.LL__c, pull);
            }
        }
        
        Map<ID, P__c> ipmap = new Map<ID, P__c>();
        
        for(P__c pull: scope){
            
            if(pull.P1__c!=Null){            
            ipmap.put(pull.P1__c,pull);
            }
            if(pull.P2__c!=Null){
            ipmap.put(pull.P2__c,pull);
            }
            if(pull.P3__c!=Null){
             ipmap.put(pull.P3__c,pull);
            }
            if(pull.P4__c!=Null){
            ipmap.put(pull.P4__c,pull);
            }
            if(pull.P5__c!=Null){
            ipmap.put(pull.P5__c,pull);
            }
            if(pull.P6__c!=Null){
            ipmap.put(pull.P6__c,pull);
            }
            if(pull.I1__c!=Null){
            ipmap.put(pull.I1__c,pull);
            }
            if(pull.I2__c!=Null){
           ipmap.put(pull.I2__c,pull);
            }
            if(pull.SU__c!=Null){
            ipmap.put(pull.SU__c,pull);
            }
            if(pull.L__c!=Null){
            ipmap.put(pull.L__c,pull);
            }
            if(pull.MN__c!=Null){
            ipmap.put(pull.MN__c,pull);
            }
            if(pull.MI__c!=Null){
            ipmap.put(pull.MI__c,pull);
            }
            if(pull.MQ__c!=Null){
            ipmap.put(pull.MQ__c,pull);
            }
            if(pull.SR__c!=Null){
            ipmap.put(pull.SR__c,pull);
            }
            if(pull.M__c!=Null){
            ipmap.put(pull.M__c,pull);
            }
        }
        
        // SOQL query to get all locations and their recent wellrundata in pullrecord location
        
        List<SVMXC__Site__c> loclist = [select id,name,(SELECT Id,Name,GE_AL_Pull__c,GE_AL_Install_Date__c,GE_AL_Pull_Date__c,GE_AL_Location__c FROM GE_AL_Wells_Run_Data__r ORDER BY CreatedDate DESC LIMIT 1) from SVMXC__Site__c where id IN : pullMap.KeySet()];        
        
        // to store wellrundata records with install date null
        
        // wrderrorlist = new List<GE_AL_Well_Run_Data__c>();
        List<GE_AL_Well_Run_Data__c> wrdsuccesslist = new List<GE_AL_Well_Run_Data__c>();
        
        for(SVMXC__Site__c loc : loclist){
            
            P__c pullrec = pullmap.get(loc.Id);
            
            for(GE_AL_Well_Run_Data__c wrd:loc.GE_AL_Wells_Run_Data__r){
                
                if(wrd.GE_AL_Pull_Date__c == Null && wrd.GE_AL_Install_Date__c != Null){
                    
                    wrd.GE_AL_Pull__c = pullrec.Id;
                    wrd.GE_AL_Pull_Date__c = pullrec.DS__c;
                    wrd.GE_AL_Reason_for_Pull__c = pullrec.PR__c;
                    wrdsuccesslist.add(wrd);
                }else{
                    wrderrorlist.add(wrd);
                } 
            } 
        }
        system.debug('wellrundata success'+wrdsuccesslist.size());
        system.debug('wellrundata error'+wrderrorlist.size());
        Database.SaveResult[] srlist = Database.update(wrdsuccesslist,false);
        
        List<SVMXC__Installed_Product__c> iplist =[select id,Name,(select id,Name,GE_AL_Install_Date__c,GE_AL_Location__c,SVMXC_Installed_Product__c,GE_AL_Pull_Date__c from Equipments_Run_Data__r ORDER BY CreatedDate DESC LIMIT 1) from SVMXC__Installed_Product__c where id in :ipmap.keyset()];
        List<GE_AL_Equipment_Run_Data__c> equipmentrundata = new List<GE_AL_Equipment_Run_Data__c>();
        
        for(SVMXC__Installed_Product__c ip : iplist){        
            for(GE_AL_Equipment_Run_Data__c erd : ip.Equipments_Run_Data__r){
            equipmentrundata.add(erd);
            }
        }
        
        system.debug('erd'+equipmentrundata.size());
        
        erderrorlist = new List<GE_AL_Equipment_Run_Data__c>();
        List<GE_AL_Equipment_Run_Data__c> erdsuccesslist = new List<GE_AL_Equipment_Run_Data__c>();
        
        for(SVMXC__Installed_Product__c ip : iplist){    
            P__c pull = ipmap.get(ip.Id);
            for(GE_AL_Equipment_Run_Data__c  erd:ip.Equipments_Run_Data__r){
                if(erd.GE_AL_Pull_Date__c == Null && erd.GE_AL_Install_Date__c != Null){
                     if(pull.P1__c != Null && pull.P1__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.P2__c != Null && pull.P2__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.P3__c != Null && pull.P3__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.P4__c != Null && pull.P4__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.P5__c != Null && pull.P5__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.P6__c != Null && pull.P6__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.I1__c != Null && pull.I1__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.I2__c != Null && pull.I2__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.SU__c != Null && pull.SU__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.L__c != Null && pull.L__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.MN__c != Null && pull.MN__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.MI__c != Null && pull.MI__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.MQ__c != Null && pull.MQ__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.SR__c != Null && pull.SR__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                        if(pull.M__c != Null && pull.M__c == erd.SVMXC_Installed_Product__c)
                        {   
                            erd.GE_AL_Pull_Date__c = pull.DS__c;
                            erdsuccesslist.add(erd);
                        }
                  
                }else{
                    erderrorlist.add(erd);
                } 
            } 
        }
        
        system.debug('equipmentrundata success'+erdsuccesslist.size());
        system.debug('equipmentrundata error'+erderrorlist.size());
        Database.SaveResult[] slist = Database.update(erdsuccesslist,false);
        
      /*  
        String msg = '';

        for(GE_AL_Well_Run_Data__c wrd:wrderrorlist){
           msg+=wrd.Id+'--';
        }
        
        for(GE_AL_Equipment_Run_Data__c erd:erderrorlist){
           msg+=erd.Id+'--';
        }
        */
        
        String body = '<table border="1"><tr> <th>Record Name</th><th>Record ID</th></tr>';
        
        for(GE_AL_Well_Run_Data__c wrd:wrderrorlist){
           body+='<tr><td>'+wrd.Name+'</td><td>'+wrd.Id+'</td></tr>';
        }
        
        for(GE_AL_Equipment_Run_Data__c erd:erderrorlist){
           body+='<tr><td>'+erd.Name+'</td><td>'+erd.Id+'</td></tr>';
        }
        
        body+='</table>';
        
      //  system.debug('in finish'+msg);
        if(wrderrorlist.size()>0 ||erderrorlist.size()>0 ){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'naveen.vuppu@ge.com','christie.huczek@ge.com'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Record not updated');
       // mail.setPlainTextBody('records failed '+msg);
        mail.setHtmlBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        }
    }
    global void finish(Database.BatchableContext BC) {   
    }
}