force-app/main/default/objects/I__c/I__c.object-meta.xml
<CustomObject>
    <description>Object created for the Install report and record creation; R-23769</description>
    <label>Install</label>
    <nameField>
        <displayFormat>Install-{000000}</displayFormat>
        <label>Install Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/I__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MLC Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (MLC Serial #)</relationshipLabel>
    <relationshipName>InstallLCWM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/DC__c.field-meta.xml
<CustomField>
    <fullName>DC__c</fullName>
    <label>Current Install: Date Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/I__c/fields/I2__c.field-meta.xml
<CustomField>
    <fullName>I2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake/Gas SEP Serial # (2)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Intake/Gas SEP Serial # (2))</relationshipLabel>
    <relationshipName>Install8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/I__c.field-meta.xml
<CustomField>
    <fullName>I__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake/Gas SEP Serial # (1)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Intake/Gas SEP Serial # (1))</relationshipLabel>
    <relationshipName>Install7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/L2__c.field-meta.xml
<CustomField>
    <fullName>L2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal Serial # (2)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Seal Serial # (2))</relationshipLabel>
    <relationshipName>InstallLCV4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal Serial # (1)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Seal Serial # (1))</relationshipLabel>
    <relationshipName>Install9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/LW__c.field-meta.xml
<CustomField>
    <fullName>LW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lease/Well Location</label>
    <referenceTo>SVMXC__Site__c</referenceTo>
    <relationshipLabel>Install</relationshipLabel>
    <relationshipName>Install</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/M2__c.field-meta.xml
<CustomField>
    <fullName>M2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor Serial # (2)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Motor Serial # (2))</relationshipLabel>
    <relationshipName>InstallLCVO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/M__c.field-meta.xml
<CustomField>
    <fullName>M__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motor Serial # (1)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Motor Serial # (1))</relationshipLabel>
    <relationshipName>InstallLCVE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P2__c.field-meta.xml
<CustomField>
    <fullName>P2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (2)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (2))</relationshipLabel>
    <relationshipName>Install1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P3__c.field-meta.xml
<CustomField>
    <fullName>P3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (3)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (3))</relationshipLabel>
    <relationshipName>Install2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P4__c.field-meta.xml
<CustomField>
    <fullName>P4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (4)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (4))</relationshipLabel>
    <relationshipName>Install3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P5__c.field-meta.xml
<CustomField>
    <fullName>P5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (5)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (5))</relationshipLabel>
    <relationshipName>Install4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P6__c.field-meta.xml
<CustomField>
    <fullName>P6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (6)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (6))</relationshipLabel>
    <relationshipName>Install5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P7__c.field-meta.xml
<CustomField>
    <fullName>P7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (7)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Pump Serial # (7))</relationshipLabel>
    <relationshipName>Install6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/P__c.field-meta.xml
<CustomField>
    <fullName>P__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump Serial # (1)</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install</relationshipLabel>
    <relationshipName>Install</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/I__c/fields/R__c.field-meta.xml
<CustomField>
    <fullName>R__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sensor Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Install (Sensor Serial #)</relationshipLabel>
    <relationshipName>InstallLCWC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/P__c.object-meta.xml
<CustomObject>
    <description>Object created for the Pull report creation; R-23768</description>
    <label>Pull</label>
    <nameField>
        <displayFormat>Pull-{000000}</displayFormat>
        <label>Pull Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pulls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P__c/fields/DC__c.field-meta.xml
<CustomField>
    <fullName>DC__c</fullName>
    <label>Current Pull: Date Job Completed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/P__c/fields/I2__c.field-meta.xml
<CustomField>
    <fullName>I2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake Gas 2 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Intake Gas 2 Serial #)</relationshipLabel>
    <relationshipName>Pulls_IntkGas_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/I__c.field-meta.xml
<CustomField>
    <fullName>I__c</fullName>
    <label>Issues</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seal LT Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Seal LT Serial #)</relationshipLabel>
    <relationshipName>Pulls_Seal_LT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/LW__c.field-meta.xml
<CustomField>
    <fullName>LW__c</fullName>
    <label>Liner Weight</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/P__c/fields/M__c.field-meta.xml
<CustomField>
    <fullName>M__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MLC Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (MLC Serial #)</relationshipLabel>
    <relationshipName>Pulls_MLC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P2__c.field-meta.xml
<CustomField>
    <fullName>P2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 2 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 2 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P3__c.field-meta.xml
<CustomField>
    <fullName>P3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 3 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 3 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P4__c.field-meta.xml
<CustomField>
    <fullName>P4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 4 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 4 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P5__c.field-meta.xml
<CustomField>
    <fullName>P5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 5 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 5 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P6__c.field-meta.xml
<CustomField>
    <fullName>P6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 6 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 6 Serial #)</relationshipLabel>
    <relationshipName>Pulls_Pump_6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P7__c.field-meta.xml
<CustomField>
    <fullName>P7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pump 7 Serial #</label>
    <referenceTo>SVMXC__Installed_Product__c</referenceTo>
    <relationshipLabel>Pulls (Pump 7 Serial #)</relationshipLabel>
    <relationshipName>Pulls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P__c/fields/P__c.field-meta.xml
<CustomField>
    <fullName>P__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/GE_AL_InstallHelper.cls
/*
Class Name                   - GE_AL_InstallHelper 
Object Name                  - Install
Created Date                 - 11/9/2016
Description                  -  Helper Class GE_AL_InstallTriggerHandler would process all the Trigger requests coming from GE_AL_InstallTrigger 
                                All Logic to be processed in the Helper Classes being executed from the Handler Class
Test Class                   -  GE_AL_InstallHelper_Test                                
*/
public with sharing class GE_AL_InstallHelper{
  public void CreateEquipmentRunData(List<I__c> lstInstalls)
  {
    List <GE_AL_Equipment_Run_Data__c> equToInsert = new List <GE_AL_Equipment_Run_Data__c> ();
    for(I__c i: lstInstalls)
    {
        if (i.P__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e = new GE_AL_Equipment_Run_Data__c ();
          e.SVMXC_Installed_Product__c = i.P__c;
          e.GE_AL_Install_Date__c = i.DC__c;
          e.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e);
        }
        if (i.P2__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P2__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.P3__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P3__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.P4__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P4__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.P5__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P5__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.P6__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P6__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.P7__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.P7__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.I__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.I__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.I2__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.I2__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.L__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.L__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.L2__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.L2__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.M__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.M__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.M2__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.M2__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.R__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.R__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
        if (i.C__c != Null)
        {
          GE_AL_Equipment_Run_Data__c e1 = new GE_AL_Equipment_Run_Data__c ();
          e1.SVMXC_Installed_Product__c = i.C__c;
          e1.GE_AL_Install_Date__c = i.DC__c;
          e1.GE_AL_Location__c = i.LW__c;
          equToInsert.add(e1);
        }
    }
    try{
        if(equToInsert.size() > 0)
        {
        insert equToInsert;
        }
    }catch(system.Dmlexception e){
        system.debug(e);
    }
  }
}